# Generated by Django 6.0 on 2025-12-26 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concours', '0002_dossier_resultat'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('statut', models.CharField(default='en_attente', max_length=20)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.candidat')),
                ('concours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concours.concours')),
            ],
        ),
    ]
