# Generated by Django 6.0 on 2025-12-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_jury_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('candidat', 'Candidat'), ('gestionnaire', 'Gestionnaire'), ('jury', 'Jury')], max_length=20),
        ),
    ]
