# Generated by Django 6.0 on 2025-12-27 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_token_valid_after'),
        ('users', '0005_alter_user_role'),
    ]

    operations = [
    ]
