# Generated by Django 6.0 on 2026-01-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_bugreport_bugevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='historique_academique',
            field=models.TextField(blank=True, help_text='Détails du parcours académique'),
        ),
    ]
