# Generated by Django 6.0 on 2025-12-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_ouverture', models.DateField()),
                ('date_fermeture', models.DateField()),
                ('frais_inscription', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
