# Generated by Django 6.0 on 2025-12-26 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='en_attente', max_length=20)),
                ('justificatif', models.FileField(blank=True, upload_to='justificatifs/')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.candidat')),
                ('concours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concours.concours')),
            ],
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('admis', models.BooleanField(default=False)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='concours.dossier')),
            ],
        ),
    ]
