# Generated by Django 6.0 on 2026-01-12 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0004_add_serie_matiere_note_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='concours.serie'),
        ),
        migrations.AlterField(
            model_name='concours',
            name='publie',
            field=models.BooleanField(default=False),
        ),
    ]
