# Generated by Django 6.0 on 2026-01-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0006_concours_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='concours',
            name='documents_requis',
            field=models.TextField(blank=True, help_text='Liste des documents requis (séparés par des virgules)'),
        ),
        migrations.AddField(
            model_name='concours',
            name='lieu_depot',
            field=models.TextField(blank=True, help_text='Adresse complète du lieu de dépôt des dossiers'),
        ),
        migrations.AddField(
            model_name='concours',
            name='limite_age_max',
            field=models.IntegerField(blank=True, help_text='Âge maximum requis (années)', null=True),
        ),
        migrations.AddField(
            model_name='concours',
            name='limite_age_min',
            field=models.IntegerField(blank=True, help_text='Âge minimum requis (années)', null=True),
        ),
        migrations.AddField(
            model_name='concours',
            name='ministere_organisateur',
            field=models.CharField(blank=True, help_text='Ministère organisateur du concours', max_length=200),
        ),
        migrations.AddField(
            model_name='concours',
            name='niveau_demande',
            field=models.CharField(blank=True, choices=[('BEPC', 'BEPC'), ('Bac', 'Bac'), ('Bac+1', 'Bac+1'), ('Bac+2', 'Bac+2'), ('Bac+3', 'Bac+3'), ('Bac+4', 'Bac+4'), ('Bac+5', 'Bac+5'), ('Bac+6', 'Bac+6 et plus')], help_text='Niveau académique minimum requis', max_length=20),
        ),
        migrations.AddField(
            model_name='concours',
            name='nombre_places',
            field=models.IntegerField(blank=True, help_text='Nombre de places disponibles', null=True),
        ),
    ]
